### ISSUE TITLE
8th schedule plan

### ISSUE THREAD

**Issue by jongfeel** [aralaa/BookJournal#14]
# 주당 총 24시간

## 평일

- 오전 9시 ~ 오후 2시, 점심시간 제외
- 하루 4시간, 총 20시간

## 주말+휴일

- 1회, 4시간

**Comment by aralaa** [comment]
4월 7일 (화)
- [x] 9시 ~ 2시 
- [x] REST API 수정
- [x] 서버 코드 작성

진행한 내용
API 경로 수정하고 바디 수정
DB bookjournal 테이블 수정 (book이랑 중복된 내용 있어서 삭제함)
바뀐 내용 위키 업데이트
서버 코드 route 수정했는데 오류 나는데 왜 나는지 몰라서 내일은 오류 찾고 수정하기

**Comment by aralaa** [comment]
4월 8일 (수)
- [x] 9시 ~ 2시

**Comment by aralaa** [comment]
4월 9일 (목) 
- [x] 10시 ~ 3시
- 늦게 일어나서 10시부터 시작했음

**Comment by aralaa** [comment]
4월 10일 (금)
- [x] 9시 ~2시

**Comment by aralaa** [comment]
4월 13일 (월)
- [x] 9시 ~ 2시

**Comment by aralaa** [comment]
@jongfeel 
## 4월 7일 (화) ~ 4월 13일 (월)
**총 20시간**
- 평일 5회, 20시간 (O)
- 주말 1회, 4시간 (X)

---
처음 계획한대로 하다 보면 모르는 부분이 나와서 찾아보는데 오래걸리고
에러가 나면 에러를 찾는데 또 오래걸리니까 4시간이 금방 지나감.
이번주에 서버 코드를 다 작성하려고 했는데 데이터베이스 모르는 부분을 공부하고
오타 같은거나 파일을 여러개 열어놓고 다른 파일을 수정하고 에러 나서
왜 에러나는지 찾는 바보같은 짓을 많이 해서 시간 낭비가 심했음.
20시간이어도 실제 진행한 내용은 router.post 코드만 작성하였다.
