### ISSUE TITLE
SQL문 정리하기

### ISSUE THREAD

**Issue by aralaa** [aralaa/BookJournal#17]
- SQL문 찾아보고 내 코드에 적용시키기
- 찾아본 내용 잘 정리해두기

**Comment by jongfeel** [comment]
정리해둔 내용을 어디서 볼 수 있을까요?

**Comment by aralaa** [comment]
노션에다 정리해뒀었는데 방금 레파지토리 파서 올렸어요
[SQL문 정리](https://github.com/aralaa/TIL/blob/master/SQL%EB%AC%B8.md)
