### ISSUE TITLE
9th schedule plan

### ISSUE THREAD

**Issue by jongfeel** [aralaa/BookJournal#20]
### 평일
- 오전 9시 ~ 오후 2시, 점심시간 제외
- 하루 4시간, 총 20시간
### 주말+휴일
- 1회, 4시간

**Comment by aralaa** [comment]
4월 14일 (화)
- [x] 9시 ~ 2시

**Comment by aralaa** [comment]
4월 15일 (수)
- [x] 9시 ~ 2시

**Comment by aralaa** [comment]
4월 17일 (목)
- [x] 9시 ~ 2시

**Comment by aralaa** [comment]
4월 25일 (토)
- [x] 12시 30분 ~ 4시 30분

**Comment by aralaa** [comment]
## 4월 14일 ~ 4월 27일
**총 16시간**
- 주중 12시간
- 주말 4시간
---
이번 기간에는 자소서 쓰고 토익 공부 때문에 프로젝트에 시간 할애를 많이 못했다.
이론적인 공부만 하고 실제 코딩은 모델 작성하는 부분까지밖에 못했다.
mocha로 테스트 코드를 작성해보려고 했는데 어떻게 작성해야 할지 감이 안잡혔다.
그래서 그냥 일단 테이블 만드는 코드 먼저 작성했다.

**Comment by jongfeel** [comment]
음 1주에 24시간 계획을 했고 2주 진행해서 16시간 한거면
33% 정도 진행한거네요.

일단 자격증하고 시험 준비 하느라 시간 못썼다고 하셨으니 특수한 상황이라고 보면 될거 같고
이후 6월부터 다시 진행할 때 계획 세우고 해보면 될 거 같습니다.

**Comment by aralaa** [comment]
## 주당 총 8시간
### 평일
- 3회, 2시간
### 주말 + 휴일
- 1회, 2시간
